"""
name_map.py — IVC Pharma Dashboard: Master Name & Entity Mapping
================================================================
Single source of truth for all entity normalization.
Import this in app.py and call normalize_*(name) before any chart or table.

Fuzzy matching threshold: 70 (safe for most pharma name variants).
For joint entries like "JITENDRA/CLEMANCE", use resolve_joint_mr().
"""

from rapidfuzz import process, fuzz

# ─────────────────────────────────────────────────────────────
# 1. MR / FIELD STAFF
# ─────────────────────────────────────────────────────────────

MR_CANONICAL = {
    "MR_001": "NELLY NIAMIEN",
    "MR_002": "CLEMANCE KOUDIANE",
    "MR_003": "JAMBA FRANCK",
    "MR_004": "AHIOUA",
    "MR_005": "TOUALY CLEVAR",
    "MR_006": "JITENDRA MISHRA",   # Country Manager (CM)
    "AGT_001": "ARRA BEHOU",       # Promo Agent (not MR)
}

# Hard-coded overrides first (exact/near-exact variants that fuzzy may miss)
MR_OVERRIDES = {
    # NELLY
    "MME NELLY": "MR_001", "MME NELLY ": "MR_001", "NELLY": "MR_001",
    "NELLY NIAMIEN": "MR_001",
    # CLEMANCE
    "MME CLEMENCE": "MR_002", "MME CLEMANCE": "MR_002", "CLEMANCE": "MR_002",
    "CALMANCE": "MR_002", "IN LIST OF CLAMANCE": "MR_002",
    "CLEMANCE KOUDIANE": "MR_002",
    # JAMBA
    "MR JAMBA FRANCK": "MR_003", "JAMBA FRANK": "MR_003",
    "JAMBA FRANCK": "MR_003", "JAMBA Franck": "MR_003", "JAMAB FRANK": "MR_003",
    # AHIOUA
    "MME AHIOUA": "MR_004", "AHIOUA": "MR_004",
    "IN LIST OF AHIOUA": "MR_004",
    # TOUALY (also appears as VALERY in Feb tracker)
    "MR TOUALY": "MR_005", "TOUALY": "MR_005", "VALERY": "MR_005",
    "MR. TOUALY CLEVAR": "MR_005", "TOUALY CLEVAR": "MR_005",
    # JITENDRA (CM)
    "MR. JITENDER": "MR_006", "JITENDRA": "MR_006",
    "MR. JITENDER MISHRA": "MR_006", "JITENDER SIR": "MR_006",
    "MR. JITENDER ": "MR_006", "JITENDRA MISHRA": "MR_006",
    "1": "MR_006",   # data entry error in report file
    # ARRA BEHOU
    "ARRA BEHOU": "AGT_001",
}

# Joint entries — map to list of IDs
MR_JOINT_MAP = {
    "JITENDRA/NELLY":    ["MR_006", "MR_001"],
    "JITENDRA/CLEMANCE": ["MR_006", "MR_002"],
    "JITENDRA/ARRA":     ["MR_006", "AGT_001"],
    "DELEGAT/CM/AGENT":  ["MR_006", "AGT_001"],
}

def normalize_mr(raw: str) -> str:
    """
    Returns canonical MR ID string.
    Joint entries return comma-separated IDs e.g. 'MR_006,MR_002'.
    Unknown returns 'UNKNOWN'.
    """
    if not raw or str(raw).strip() in ("", "nan"):
        return "UNKNOWN"
    clean = str(raw).strip()
    
    # Check joint entries first
    clean_upper = clean.upper()
    if clean_upper in MR_JOINT_MAP:
        return ",".join(MR_JOINT_MAP[clean_upper])
    
    # Check hard overrides
    if clean_upper in MR_OVERRIDES:
        return MR_OVERRIDES[clean_upper]
    
    # Fuzzy fallback — strip common prefixes before matching
    stripped = clean_upper
    for prefix in ["MME ", "MR. ", "MR ", "MS. ", "MS ", "IN LIST OF "]:
        stripped = stripped.replace(prefix, "")
    stripped = stripped.strip()
    
    candidates = list(MR_CANONICAL.values())
    match, score, _ = process.extractOne(
        stripped, [c.upper() for c in candidates], scorer=fuzz.token_sort_ratio
    )
    if score >= 70:
        # Return ID from canonical dict
        for id_, name in MR_CANONICAL.items():
            if name.upper() == match:
                return id_
    return "UNKNOWN"

def mr_display_name(mr_id: str) -> str:
    """Convert MR_001 -> 'NELLY NIAMIEN'. Handles comma-separated joint IDs."""
    if "," in mr_id:
        return " + ".join(MR_CANONICAL.get(i, i) for i in mr_id.split(","))
    return MR_CANONICAL.get(mr_id, mr_id)


# ─────────────────────────────────────────────────────────────
# 2. PRODUCTS
# ─────────────────────────────────────────────────────────────

PRODUCT_CANONICAL = {
    "P_001": "COZEE 60",
    "P_002": "COZEE 90",
    "P_003": "COZEE 120",
    "P_004": "FEZEE",
    "P_005": "FUSIZEX 40",       # Tablet
    "P_006": "KLINDEX-M",
    "P_007": "NOSEE",
    "P_008": "OMEZEE 20",
    "P_009": "PROZEE 100",
    "P_010": "CITIZEN INJ",
    "P_011": "FUSIZEX INJ",       # Injectable
    "P_012": "AVETEX INJ",
    "P_013": "BETNEZEN INJ",
    "P_014": "HEMOTRATE INJ",
    "P_015": "OMECID INJ",
    "P_016": "STURIX INJ",
}

PRODUCT_OVERRIDES = {
    # COZEE family
    "COZEE 60": "P_001", "COZEE60": "P_001",
    "COZEE 90": "P_002", "COZEE90": "P_002",
    "COZEE 120": "P_003", "COZEE120": "P_003",
    "COZEE": None,  # too ambiguous — skip, flag separately
    # FEZEE
    "FEZEE": "P_004", "FEZEE GELU BT 10": "P_004",
    # FUSIZEX tablet
    "FUSIZEX 40": "P_005", "FUSIZEX 40MG CPR BOITE DE 30": "P_005",
    # KLINDEX-M (typo variant KLINDEZ-M)
    "KLINDEX-M": "P_006", "KLINDEZ-M": "P_006",
    "KLINDEX M 100MG CAPS VAG BT 7": "P_006", "KLINDEX": "P_006",
    # NOSEE (typo variant NOZEE)
    "NOSEE": "P_007", "NOZEE": "P_007",
    "NOSEE 10MG/10MG CPR BT 30": "P_007",
    # OMEZEE
    "OMEZEE 20": "P_008", "OMEZEE": "P_008",
    "OMEZEE 20MG GELU BT 10": "P_008",
    # PROZEE
    "PROZEE 100": "P_009", "PROZEE": "P_009",
    # CITIZEN INJ
    "CITIZEN- INJ": "P_010", "CITIZEN INJ": "P_010", "CITIZEN": "P_010",
    "CITIZEN 1000MG/4ML B/5AMP (CITICOLINE INJ 1G/4ML)": "P_010",
    "CITIZEN 1000MG SOL INJ 5 AMP": "P_010",
    # FUSIZEX INJ
    "FUSIZEX-INJ": "P_011", "FUSIZEX INJ": "P_011",
    "FUSIZEX 10MG/ML (FUROSEMIDE 10MG/ML)": "P_011",
    "FUSIZEX 10MG SOL INJ AMP B10": "P_011",
    "FUSIZEX 10": "P_011",
    # AVETEX INJ (typo: AVTEX)
    "AVETEX-INJ": "P_012", "AVETEX INJ": "P_012",
    "AVETEX 500MG INJ B/1AMP": "P_012",
    "AVETEX 500MG PDR SOL PERF FL 1": "P_012",
    "AVETEX": "P_012", "AVTEX": "P_012",
    # BETNEZEN INJ
    "BETNEZEN-INJ": "P_013", "BETNEZEN INJ": "P_013",
    "BETNEZEN 4MG/ML B/5AMP": "P_013",
    "BETNEZEN SOL INJ AMP BT 5X1ML": "P_013", "BETNEZEN": "P_013",
    # HEMOTRATE INJ
    "HEMOTRATE-INJ": "P_014", "HEMOTRATE INJ": "P_014",
    "HEMOTRATE-S B/5AMP": "P_014",
    "HEMOTRATE-S SOL INJ AMP 5X5ML": "P_014", "HEMOTRATE": "P_014",
    # OMECID INJ (trailing comma variant)
    "OMECID INJ": "P_015", "OMECID 40 MG INJ  B 1AMP": "P_015",
    "OMECID 40MG PDR SOL PERF FL 1": "P_015",
    "OMECID": "P_015", "OMECID,": "P_015",
    # STURIX INJ
    "STURIX-INJ": "P_016", "STURIX INJ": "P_016",
    "STURIX 500MG/5ML B/5AMP": "P_016",
    "STURIX 500MG SOL INJ AMP 5X5ML": "P_016", "STURIX": "P_016",
    # DISCONTINUED / NOT OUR PRODUCTS — explicitly excluded
    "ARTEQUIN LACTAB 300/375 BT6": None,
    "ARTEQUIN LACTAB 600/750 BT6": None,
    "LETROVIN 2,5MG CPR BOITE 30": None,
    "AVETEX(417 ) DEC-& JAN": "P_012",  # historical label, map to AVETEX INJ
}

PRODUCT_CATEGORIES = {
    "P_001": "TABLET", "P_002": "TABLET", "P_003": "TABLET",
    "P_004": "TABLET", "P_005": "TABLET", "P_006": "TABLET",
    "P_007": "TABLET", "P_008": "TABLET", "P_009": "TABLET",
    "P_010": "INJECTABLE", "P_011": "INJECTABLE", "P_012": "INJECTABLE",
    "P_013": "INJECTABLE", "P_014": "INJECTABLE",
    "P_015": "INJECTABLE", "P_016": "INJECTABLE",
}

def normalize_product(raw: str) -> str:
    """Returns product ID. None = excluded. 'UNKNOWN' = not recognized."""
    if not raw or str(raw).strip() in ("", "nan"):
        return "UNKNOWN"
    clean = str(raw).strip().upper()
    if clean in PRODUCT_OVERRIDES:
        result = PRODUCT_OVERRIDES[clean]
        return result if result is not None else "EXCLUDED"
    # Fuzzy fallback
    candidates = list(PRODUCT_CANONICAL.values())
    match, score, _ = process.extractOne(
        clean, [c.upper() for c in candidates], scorer=fuzz.token_sort_ratio
    )
    if score >= 75:
        for id_, name in PRODUCT_CANONICAL.items():
            if name.upper() == match:
                return id_
    return "UNKNOWN"

def product_display_name(product_id: str) -> str:
    return PRODUCT_CANONICAL.get(product_id, product_id)

def product_category(product_id: str) -> str:
    return PRODUCT_CATEGORIES.get(product_id, "UNKNOWN")


# ─────────────────────────────────────────────────────────────
# 3. ACTIVITY TYPES
# ─────────────────────────────────────────────────────────────

ACTIVITY_CANONICAL = {
    "ACT_COMMISSION":      "COMMISSION",
    "ACT_MOTIVATION":      "MOTIVATION",
    "ACT_PETIT_DEJ":       "PETIT DEJEUNER",
    "ACT_GARD":            "GARD ACTIVITY",
    "ACT_PARTNERSHIP":     "PARTNERSHIP",
    "ACT_CME":             "CME",
    "ACT_INJ_COMMISSION":  "INJECTABLE COMMISSION",
    "ACT_WINE":            "WINE",
    "ACT_KIT_SAVON":       "KIT DE SAVON",
    "ACT_PAGNE":           "PAGNE",
    "ACT_STAMP":           "STAMP",
    "ACT_SAMPLE":          "SAMPLE",
}

ACTIVITY_OVERRIDES = {
    "COMMISSION": "ACT_COMMISSION", "COMISSION": "ACT_COMMISSION",
    "MOTIVATION": "ACT_MOTIVATION", "MOTIVATION ": "ACT_MOTIVATION",
    "PETIT DEJOUNER": "ACT_PETIT_DEJ", "PETITE DEJOUNER": "ACT_PETIT_DEJ",
    "PETITE DEJEUNER": "ACT_PETIT_DEJ", "PETIT DEJEUNER": "ACT_PETIT_DEJ",
    "GARD ACTIVITY": "ACT_GARD", "GARD": "ACT_GARD",
    "PARTNERSHIP": "ACT_PARTNERSHIP",
    "CME": "ACT_CME", "CME PLAN": "ACT_CME",
    "INJECTABLE COMMISSION": "ACT_INJ_COMMISSION",
    "WINE": "ACT_WINE",
    "KIT DE SAVON": "ACT_KIT_SAVON", "KIT SAVON": "ACT_KIT_SAVON",
    "PAGNE": "ACT_PAGNE",
    "STAMP": "ACT_STAMP",
    "SAMPLE PROZEE": "ACT_SAMPLE", "SAMPLE": "ACT_SAMPLE",
}

def normalize_activity(raw: str) -> str:
    if not raw or str(raw).strip() in ("", "nan"):
        return "UNKNOWN"
    clean = str(raw).strip().upper()
    if clean in ACTIVITY_OVERRIDES:
        return ACTIVITY_OVERRIDES[clean]
    match, score, _ = process.extractOne(
        clean, list(ACTIVITY_OVERRIDES.keys()), scorer=fuzz.token_sort_ratio
    )
    if score >= 75:
        return ACTIVITY_OVERRIDES[match]
    return "UNKNOWN"

def activity_display_name(act_id: str) -> str:
    return ACTIVITY_CANONICAL.get(act_id, act_id)


# ─────────────────────────────────────────────────────────────
# 4. TERRITORIES / ZONES
# ─────────────────────────────────────────────────────────────

TERRITORY_CANONICAL = {
    "ZONE_YOP_WEST":  "YOPOUGON WEST",
    "ZONE_YOP_EAST":  "YOPOUGON EAST",
    "ZONE_COCODY":    "COCODY",
    "ZONE_ADJAME":    "ADJAME",
    "ZONE_MARCORI":   "MARCORI + KOUMASSI",
}

TERRITORY_OVERRIDES = {
    "YOPOUGON OUEST": "ZONE_YOP_WEST", "YOUPOUGON WEST": "ZONE_YOP_WEST",
    "YOPOUGON QUEST": "ZONE_YOP_WEST", "YOPOUGON WEST": "ZONE_YOP_WEST",
    "YOPOUGON EAST": "ZONE_YOP_EAST", "YOUPOUGON EAST": "ZONE_YOP_EAST",
    "YOPOUGON EST": "ZONE_YOP_EAST",
    "COCODY": "ZONE_COCODY", "COCODI": "ZONE_COCODY",
    "ADJAME": "ZONE_ADJAME", "ADJAME +ATTACOUBE": "ZONE_ADJAME",
    "ADJAME/ATTACOUBE": "ZONE_ADJAME",
    "MARCORI+KOUMASSI": "ZONE_MARCORI",
    "KOUMASSI+MARCORI+PORT BOUET": "ZONE_MARCORI",
    "MARCORI + KOUMASSI": "ZONE_MARCORI",
}

def normalize_territory(raw: str) -> str:
    if not raw or str(raw).strip() in ("", "nan"):
        return "UNKNOWN"
    clean = str(raw).strip().upper()
    if clean in TERRITORY_OVERRIDES:
        return TERRITORY_OVERRIDES[clean]
    match, score, _ = process.extractOne(
        clean, list(TERRITORY_OVERRIDES.keys()), scorer=fuzz.token_sort_ratio
    )
    if score >= 75:
        return TERRITORY_OVERRIDES[match]
    return "UNKNOWN"

def territory_display_name(zone_id: str) -> str:
    return TERRITORY_CANONICAL.get(zone_id, zone_id)


# ─────────────────────────────────────────────────────────────
# 5. DOCTOR NAMES
# ─────────────────────────────────────────────────────────────

DOCTOR_CANONICAL = {
    "DOC_001": "Dr ABOUSSOU STEPHANE",
    "DOC_002": "Dr KOUROUMA WASSIRIKI",
    "DOC_003": "Dr KRABOU SIDNEY",
    "DOC_004": "Dr DOSSO AICHA",
    "DOC_005": "Dr OUATTARA YAYA",
    "DOC_006": "Dr INAGO CEDRIC",
    "DOC_007": "Dr LOKOU ADJOH",
    "DOC_008": "Dr N'KON KOUAME",
    "DOC_009": "Dr YAF KRA KOFFI",
    "DOC_010": "Dr ASSI BRICE",
    "DOC_011": "Dr ASSOUMA RITA",
    "DOC_012": "Dr TRAORE MEDE",
    "DOC_013": "Dr TOUALY MADOCHE",
    "DOC_014": "Dr TANOE ROSE",
    "DOC_015": "Dr GNOUHOUR YAHE",
    "DOC_016": "Dr MELEDJE GRACE",
    "DOC_017": "Dr ALEGRA ABRAKON",
    "DOC_018": "Dr AMON SIDONIE",
    "DOC_019": "Dr OGOU VALENTIN",
    "DOC_020": "Dr DJOUMAN AUDREY",
    "DOC_021": "Dr DONGO KOUAME",
    "DOC_022": "Dr AMON ANGE",
    "DOC_023": "IDE KOFFIF KOUAME",
    "DOC_024": "Dr KOUAKOU ESTELLRE",
    "DOC_025": "Dr TAH BI JULES",
    "DOC_026": "Dr BAMBA MALIKA",
    "DOC_027": "Dr N'GUESSAN DIARASSOUBA",
    "DOC_028": "Dr KOUADIO BAISSA",
    "DOC_029": "Dr N'ZI YAO",
    "DOC_030": "Dr KABORE GEDEON",
    "DOC_031": "Dr AHONON RICHARD",
    "DOC_032": "Dr AMANI ANZIAN",
    "DOC_033": "Dr ASSANDE GUILLAUME",
    "DOC_034": "IDE TCHOUMOU NATALIE",
    "DOC_035": "IDE EBONI EZECKIEL",
    "DOC_036": "Dr YAO YANN",
    "DOC_037": "Dr MANGOUA PAUL",
    "DOC_038": "Dr KONAN LUC",
    "DOC_039": "Dr BILE EKRA",
    "DOC_040": "Dr JACQUES KOUAKOU",
    "DOC_041": "SF BOKA Epse KOUAME",
    "DOC_042": "Dr KOUAME STEPHANE",
    "DOC_043": "Dr KOUSSAN FRANCOIS",
    "DOC_044": "Dr AWA ATTE",
    "DOC_045": "Dr ASSI ANGBA BRICE",
    "DOC_046": "Dr EDI BOFFOU",
    "DOC_047": "IDE GBEGOU MOIEL",
    "DOC_048": "Dr KPEA IVAN CEDRIC",
    "DOC_049": "Dr KOUASSI KOFFI",
    "DOC_050": "Dr MENOIT GREGOIRE",
    "DOC_051": "Dr KOUASSI NHEL",
    "DOC_052": "Dr GILE MOHAMED",
    "DOC_053": "SF BELLOU ARIANE",
    "DOC_054": "IDE AKA TANDJI HONORE",
    "DOC_055": "Dr KONDJI K. OZEH",
    "DOC_056": "Dr KONAN JOACHIN",
    "DOC_057": "Dr OUATTARA EL YATA",
    "DOC_058": "Dr BAH GRAH GYRI",
    "DOC_059": "IDE KOUADIO SERGE",
    "DOC_060": "Dr MENOIT MAHI DOUGLAS",
    "DOC_061": "Dr KOUAME CLAVER",
    "DOC_062": "IDE AKA JEAN RENE",
    "DOC_063": "IDE YOBOU epse ADDN",
    "DOC_064": "SF AKE ROSANI",
    "DOC_065": "SF DIALLO Née KOUAME",
    "DOC_066": "SF SONAN ANDRE H",
    "DOC_067": "Dr FENI ROSINI",
    "DOC_068": "Dr BILE BERTRAND",
    "DOC_069": "Dr BAH LUCIEN",
    "DOC_070": "Dr DOHI BI GOA L",
    "DOC_071": "Dr KONE ADAMA",
    "DOC_072": "Dr KOUAKOU GINETE",
    "DOC_073": "Dr N'GUESSAN K. ETIENNE",
    "DOC_074": "IDE KONE DRAMANE",
    "DOC_075": "Dr KPEL N'GUESSAN",
    "DOC_076": "Dr MFOUMANE DOUGLAS",
    "DOC_077": "IDE SOUMAHORO LASSINA",
    "DOC_078": "IDE KOUASSI GNANGRE",
    "DOC_079": "Dr ODEHE ANNICK",
    "DOC_080": "Dr ALLEGRA ABRAHAM",
    "DOC_081": "SF TRAORE BIN TOU",
    "DOC_082": "Dr ALLO BOU",
    "DOC_083": "Dr VEDGOUNOU ROMEO",
    "DOC_084": "IDE ANOMA ELISABETH",
    "DOC_085": "IDE KOUAME AHOU A.",
    "DOC_086": "SF YAO née BROU AKISSI",
    "DOC_087": "SF DIALLO Née SANFO",
    "DOC_088": "Dr YEO KPOUNOU ASSITA",
    "DOC_089": "Dr NARCISSE KOUADIO",
    "DOC_090": "Dr KOFFI KOUASSI KANI",
    "DOC_091": "Dr DIAGRA OFELA I.",
    "DOC_092": "Dr KOFFI PARFAIT",
    "DOC_093": "Dr GNAHORE DAVID",
    "DOC_094": "Dr MENOIT GREGOIRE H.",
    "DOC_095": "Dr AHEBROU F.",
    "DOC_096": "IDE AMIAN BEATRICE",
    "DOC_097": "Dr KOUAKOU YAH",
    "DOC_098": "ACHO ROMEO",
    "DOC_099": "Dr AKA PASCAL",
    "DOC_100": "Dr KASSI CHRISTOPHE",
    "DOC_101": "Dr KOFFI AYA ROSINE F.",
    "DOC_102": "SF EDI MARIE",
    "DOC_103": "SF KOFFI Née KOUADJO",
    "DOC_104": "SF SANOGO Née DIARRASO",
    "DOC_105": "SF KOFFI Née DJAKANA",
    "DOC_106": "IDE HOUEGNON RODRIGUE",
    "DOC_107": "Dr YAO KOUAKOU",
    "DOC_108": "Dr N'GUESSAN HELENE",
    "DOC_109": "IDE YAO HELENE",
    "DOC_110": "Dr GAUZE JEAN CLAUDE",
    "DOC_111": "IDE YAO KOUADIO ALFRED",
    "DOC_112": "Dr N'DA TOTHU D. N.",
    "DOC_113": "IDE AKOTO GUIA M.",
    "DOC_114": "Dr YAO KOFFI MATHURIN",
    "DOC_115": "Dr CISSE FATIMATA",
    "DOC_116": "IDE TENI ANGELIQUE",
    "DOC_117": "Dr AMATA ERIC",
    "DOC_118": "Dr GOUESSE Y. PATRICE",
    "DOC_119": "Dr KPELE YABA B.",
    "DOC_120": "Koffi Didier",
    "DOC_121": "Touré taha épouse kouamé",
    "DOC_122": "Adjouman Hervé",
    "DOC_123": "Balou Diop",
    "DOC_124": "Botti Lou Nédège",
    "DOC_125": "N'guessan Valerie",
    "DOC_126": "Esnel Franck",
    "DOC_127": "Diallou Gérald",
    "DOC_128": "Bodel Parfait",
    "DOC_129": "Bodel Hyacinthe",
    "DOC_130": "Bawar Firmin",
    "DOC_131": "Abdallah Becoüé",
    "DOC_132": "Kone Ibrahim",
    "DOC_133": "Allimi Lawal",
    "DOC_134": "Kto Eugénie",
    "DOC_135": "Bansanon fortune",
    "DOC_136": "Ného Moise",
    "DOC_137": "Bami Ismaél",
    "DOC_138": "Niho Marie",
    "DOC_139": "Yacine Malick",
    "DOC_140": "Agbo Niam Nazaire",
    "DOC_141": "Diomandé Katienou",
    "DOC_142": "Gnankey Venise",
    "DOC_143": "N'Dri",
    "DOC_144": "Douzoua Marc",
    "DOC_145": "Mc Amalo",
    "DOC_146": "Tano Simon",
    "DOC_147": "N' Taye Seu Nomanto",
    "DOC_148": "Akahou Stéphanie",
    "DOC_149": "Datamla Koné",
    "DOC_150": "Koffi Charles",
    "DOC_151": "Gulai Gbaza Adéla",
    "DOC_152": "Dimassouba Tchlagban Alassane",
    "DOC_153": "Kto Pauline",
    "DOC_154": "Kouamé Lou Élodie",
    "DOC_155": "Oke",
    "DOC_156": "Kochi Thierry Aime",
    "DOC_157": "Ette Goulou",
    "DOC_158": "Kone Achille",
    "DOC_159": "Alassane agiba",
    "DOC_160": "Rodrigue Kassi N'guessan",
    "DOC_161": "Yapi Eric",
    "DOC_162": "Denhe Charles Emmanuel",
    "DOC_163": "Kessé Chimène",
    "DOC_164": "Kpota Bongo lucis",
    "DOC_165": "Kassi Kadjo Martine",
    "DOC_166": "Dindji Salomon",
    "DOC_167": "N'guessan Guillaume Landry",
    "DOC_168": "Méité Alizeta",
    "DOC_169": "Zaouli lou Ange",
    "DOC_170": "Sikali Aristide",
    "DOC_171": "Anka Zéphyrin",
    "DOC_172": "Koussi Aman florentine",
    "DOC_173": "Wassiou Oro Siriya Oro Wassiou",
    "DOC_174": "Barry Ismael",
    "DOC_175": "Kra Koudio Honoré",
    "DOC_176": "Tiero Kadia Riang",
    "DOC_177": "Adballah (0208214603)",
    "DOC_178": "Assia Migneli",
    "DOC_179": "Djamala Ahou",
    "DOC_180": "Assiave Lité",
    "DOC_181": "Fadiga Nadia",
    "DOC_182": "Beda Jean Alphonse",
    "DOC_183": "Bakayoko Haroun",
    "DOC_184": "Bodolo Ignace",
    "DOC_185": "Digbe Magali",
    "DOC_186": "N' MOula Sandrine Jacky",
    "DOC_187": "Balo Mireille",
    "DOC_188": "Sourakata Camara",
    "DOC_189": "Irie Samuel",
    "DOC_190": "Romaric Kouakou",
    "DOC_191": "Konin Mialia",
    "DOC_192": "Mamadou Coulibaly",
    "DOC_193": "Koua Abouli kouakou",
    "DOC_194": "Kouacou Anka Adjo",
    "DOC_195": "Klaido Odile",
    "DOC_196": "Kalogo Arafat",
    "DOC_197": "Aboni yves roland koffi",
    "DOC_198": "Sanoko facima",
    "DOC_199": "Konan bohoussou zene carole",
    "DOC_200": "Bahi junior",
    "DOC_201": "Kouakou kouadio",
    "DOC_202": "Seka Cherif Lacina",
    "DOC_203": "Doumbia moussa",
    "DOC_204": "Cisse sabary",
    "DOC_205": "Kouassi alfred",
    "DOC_206": "Kra Idriss ouattara",
    "DOC_207": "Kouame infou faustin",
    "DOC_208": "Coulibaly timan",
    "DOC_209": "Loizoh louame",
    "DOC_210": "N'guessan kouame",
    "DOC_211": "Gouandeu nicaise",
    "DOC_212": "Toure myriam",
    "DOC_213": "Julie Romeo",
    "DOC_214": "Konan Pacome",
    "DOC_215": "Diallo cheick Oumar",
    "DOC_216": "kone Sombo",
    "DOC_217": "Coulibaly Alilce",
    "DOC_218": "Kpasso Marina",
    "DOC_219": "Kouakou julien",
    "DOC_220": "tiada Aminata Touré",
    "DOC_221": "Touré pamigean",
    "DOC_222": "kassogué marlence",
    "DOC_223": "Adja Magboir",
    "DOC_224": "ougonou Marina",
    "DOC_225": "Sirie Hypolite Fulgence",
    "DOC_226": "Bila Arignan Estelle",
    "DOC_227": "Quihi Adèle",
    "DOC_228": "Adougra Abraham",
    "DOC_229": "Kanamoko",
    "DOC_230": "Segbeng Hermana",
    "DOC_231": "Dené Fatoumata",
    "DOC_232": "lapa Evelyne",
    "DOC_233": "konan Bénédicte",
    "DOC_234": "Diorassouba Aminata",
    "DOC_235": "Mr Simon",
    "DOC_236": "Quedraogo Layeul",
    "DOC_237": "Kouadio Wilfried",
    "DOC_238": "Kouakou Sandrine",
    "DOC_239": "Alleh Yannick",
    "DOC_240": "Bamba Nawa Cheiff",
    "DOC_241": "Kouadio louis janvier",
    "DOC_242": "AG Eulyone",
    "DOC_243": "ZOUE URBAIN",
    "DOC_244": "ASSANDE RUNDE",
    "DOC_245": "SOUMAHORO SALIMATA",
    "DOC_246": "YAYA RIBECA",
    "DOC_247": "KOUASSI ZAKOUA",
    "DOC_248": "KOUADIO SAMUEL",
    "DOC_249": "AGAFOU BERTRAND",
    "DOC_250": "GNAGNE VALERIE",
    "DOC_251": "BODJI LOUIS",
    "DOC_252": "GOZE ANDRE",
    "DOC_253": "ABOU FELIX",
    "DOC_254": "KOUASSI YAO",
    "DOC_255": "AGBEDJE BÉATRICE",
    "DOC_256": "JEAN CLAUDE NADO",
    "DOC_257": "GOUELI ARISTIDE",
    "DOC_258": "DAHIN JEAN",
    "DOC_259": "ZAMPOL SILIMANE",
    "DOC_260": "PKLE N'GUESSAN",
    "DOC_261": "KAKOU AMBROISINE",
    "DOC_262": "KOUAME BORIS",
    "DOC_263": "ZEDJA GEDEON",
    "DOC_264": "NGUESSAN ALPHONSE",
    "DOC_265": "TOURE KILOUFOUOH",
    "DOC_266": "COULIBALY GNATIOLO",
    "DOC_267": "DIOMANDE HAMED",
    "DOC_268": "BROU MICHEL",
    "DOC_269": "GOGBEU ELYSE",
    "DOC_270": "ZAOULI BI ARNAUD",
    "DOC_271": "KENGANI ALPHONSE",
    "DOC_272": "BENIE N'DA",
    "DOC_273": "TOURE BIMAILA",
    "DOC_274": "AFFINGEL",
    "DOC_275": "KOUMON GHISLAIN",
    "DOC_276": "COULIBALY AMINATA",
    "DOC_277": "AFFOUMANI DOUGLAS",
    "DOC_278": "KONAN ARSENE",
    "DOC_279": "OUATTARA",
    "DOC_280": "KOUAD ANDERSON",
    "DOC_281": "KINIMISSIBO SIKA",
    "DOC_282": "FAYE ESSETCHI",
    "DOC_283": "GBONA AMBROISE",
    "DOC_284": "PAUL MEMEL",
    "DOC_285": "AW TIDIANE",
    "DOC_286": "BEUGRE ESMEL",
    "DOC_287": "VODOUNOU ROMEO",
    "DOC_288": "DOH GUY",
    "DOC_289": "AGA PATRICK",
    "DOC_290": "GNEGA GNABRY",
    "DOC_291": "OUATTARA MARIAM",
    "DOC_292": "OUFFOUE ROXANNE",
    "DOC_293": "SEKONGO NAHOUA",
    "DOC_294": "MIME ANOUABA ROME",
    "DOC_295": "NEA TIDE",
    "DOC_296": "ABO REIJE",
    "DOC_297": "BOUSCHOL OUA LABINE",
    "DOC_298": "NORO",
    "DOC_299": "GNAGNON ROXANNE",
    "DOC_300": "NAKAYOKO BIN TOU",
    "DOC_301": "ROLAND AMOUYON",
    "DOC_302": "YCHIKA ANGE",
    "DOC_303": "KOUAKOU AHOU BOSTLINE",
    "DOC_304": "WANGBANA AWA",
    "DOC_305": "KONE KANAKONON",
    "DOC_306": "SALIFOU TEHINI",
    "DOC_307": "LOU BI INI",
    "DOC_308": "GBEHE TOU ANARETE",
    "DOC_309": "AHI N'GESSAN",
    "DOC_310": "SEKONGO FATOUMATA",
    "DOC_311": "SIAHE GERMAIN",
    "DOC_312": "KOUAME MICHAEL",
    "DOC_313": "KOUASSI VIVIANE",
    "DOC_314": "JULIEN MARCEL",
    "DOC_315": "KOUADIO BERNADETTE",
    "DOC_316": "BABILE BONIFACE",
    "DOC_317": "KOFFI N'DRI",
    "DOC_318": "OLIVIER KOUADIO",
    "DOC_319": "BASSAN JONAS",
    "DOC_320": "N'DRI ALEXANDRE",
    "DOC_321": "DOSSO MAMADOU",
    "DOC_322": "GOULI CHERIE",
    "DOC_323": "IBADO FÉLIX",
    "DOC_324": "BADO NOUVOU",
    "DOC_325": "WILLY MEMEL",
    "DOC_326": "INOTTI PRISCA",
    "DOC_327": "WANGRAGUA ABOUBAKAR",
    "DOC_328": "YAGUE MARCEL",
    "DOC_329": "SAGOU MARIE SOLANGE",
    "DOC_330": "TOFANA",
    "DOC_331": "ABO YOUSSOUF",
    "DOC_332": "EUGENE TANDJI",
    "DOC_333": "AKRE PIERRE",
    "DOC_334": "SEHME YACOUBA",
    "DOC_335": "DODO MARIE JOSEE",
    "DOC_336": "SERWE SALIF",
    "DOC_337": "ROA KOUASSI",
    "DOC_338": "GAMI RI",
    "DOC_339": "ZORON CHEICK",
    "DOC_340": "CAMARA KARIM",
    "DOC_341": "LOBE LILIANE",
    "DOC_342": "KOUAME AXELLE",
    "DOC_343": "KOFFI ARSÈNE",
    "DOC_344": "KONE AICHA",
    "DOC_345": "SOKOUA LOUISE",
    "DOC_346": "GOUE GONTO BORIS",
    "DOC_347": "KONE DRAMANE",
    "DOC_348": "GOULI KOUADIO",
    "DOC_349": "KONAN NARCISSE",
    "DOC_350": "GNAGNE FREDERIC",
    "DOC_351": "APKA ESMEL",
    "DOC_352": "ESMELY INGRID",
    "DOC_353": "KANGA PARFAIT",
    "DOC_354": "TOUE APOLLINE",
    "DOC_355": "OULAI CYPRIEN",
    "DOC_356": "KOUADIO MARIUS",
    "DOC_357": "APKA RACHELLE",
    "DOC_358": "REAMY BAZIE",
    "DOC_359": "KOFFI ALEXIS",
    "DOC_360": "DIARRA MOHAMED",
    "DOC_361": "KADJA ANOH",
    "DOC_362": "KONE FANTAMAN",
    "DOC_363": "Dr gansere David",
    "DOC_364": "Dr mapout bienvenue",
    "DOC_365": "Dr Chared Eddicho",
    "DOC_366": "Dr kouadosu Francis",
    "DOC_367": "dr n'djere",
    "DOC_368": "Dr kouassi Landry",
    "DOC_369": "dr kouakou amenan Nathalie",
    "DOC_370": "dr nikadi dylane",
    "DOC_371": "dr akandia aka olive",
    "DOC_372": "dembele Hamed",
    "DOC_373": "Dr biami Diane",
    "DOC_374": "kandam herna",
    "DOC_375": "dr Yamara Myriam",
    "DOC_376": "Dr Dipoo Philippe",
    "DOC_377": "Dr agbo Ana",
    "DOC_378": "Konan Emma Konaté",
    "DOC_379": "Dr youkam Roctand",
    "DOC_380": "Mr kpakpo germain",
    "DOC_381": "mr ouadvejo",
    "DOC_382": "mme Djikano judith",
    "DOC_383": "mr ouadraogo Abdoul",
    "DOC_384": "mme n'dri Rachelle",
    "DOC_385": "mme Konan Emilie",
    "DOC_386": "mme gogbo Martine",
    "DOC_387": "mr akpoesa azouba",
    "DOC_388": "mme aore gràce",
    "DOC_389": "mme Touré marie Tano",
    "DOC_390": "mme n'takpe Marthe",
    "DOC_391": "mme Anthony Tatiana",
    "DOC_392": "mme bouatongu habiba",
    "DOC_393": "mme kouadio Sandrine",
    "DOC_394": "mme Datte Fatouma",
    "DOC_395": "mme Ouroho",
    "DOC_396": "mme aicha Adeline",
    "DOC_397": "mme aboussou Nicole",
    "DOC_398": "mme Diomande",
    "DOC_399": "pr odjalu",
    "DOC_400": "mme n'golo Dr",
    "DOC_401": "dr koffi o",
    "DOC_402": "dr Diomande zenab",
    "DOC_403": "Dr kouadio iol",
    "DOC_404": "dr Tano",
    "DOC_405": "dr aghaodra",
    "DOC_406": "dr Barry",
    "DOC_407": "Dr macoto",
    "DOC_408": "dr atounmi",
    "DOC_409": "cva tihio",
    "DOC_410": "dr Ouattara",
    "DOC_411": "dr dao a",
    "DOC_412": "ya koua",
    "DOC_413": "dr kassa",
    "DOC_414": "dr yao",
    "DOC_415": "Dr gendo Idrich",
    "DOC_416": "dr Konan",
    "DOC_417": "dr ouan",
    "DOC_418": "dr moromo",
    "DOC_419": "pr alla numba",
    "DOC_420": "dr bekooa",
    "DOC_421": "dr Coulibaly",
    "DOC_422": "dr bom flora",
    "DOC_423": "dr matheaat",
    "DOC_424": "dr yapi Bénédicte",
    "DOC_425": "dr Toua",
    "DOC_426": "dr babatunde",
    "DOC_427": "dr inahouno",
    "DOC_428": "dr abouba",
    "DOC_429": "dr rongwa Tancin",
    "DOC_430": "dr tresek brascam",
    "DOC_431": "dr tresek Tescok Mary",
    "DOC_432": "dr Ooouh",
    "DOC_433": "dr baaa",
    "DOC_434": "mayo",
    "DOC_435": "dr casey aime",
    "DOC_436": "dr Coulibaly Yaya",
    "DOC_437": "dr bamba Aboubacar",
    "DOC_438": "de bpami Nina",
    "DOC_439": "dr ouahou kasya",
    "DOC_440": "dr bana Paul",
    "DOC_441": "dr bom kouadio",
    "DOC_442": "mme couasty",
    "DOC_443": "dr rita",
    "DOC_444": "dr meite",
    "DOC_445": "dr Hamid lala",
    "DOC_446": "dr Diomande Mohamed",
    "DOC_447": "dr meite Marina",
    "DOC_448": "dr ouattari djakoury",
    "DOC_449": "pr Ag Essilier",
    "DOC_450": "dr kouadio Roseline",
    "DOC_451": "dr kokro Michel",
    "DOC_452": "dr mare marian",
    "DOC_453": "dr suisa Vianney",
    "DOC_454": "dr Edi meelyne",
    "DOC_455": "dr niahe Vianney",
    "DOC_456": "dr diaba deni",
    "DOC_457": "dr diaba louaeco",
    "DOC_458": "dr Ettienango",
    "DOC_459": "dr oaho Sandrine",
    "DOC_460": "dr Touré angelle",
    "DOC_461": "dr ouhongo",
    "DOC_462": "dr mahio Dominique",
    "DOC_463": "dr tchoumou Christophe",
    "DOC_464": "dr moitam Nediou",
    "DOC_465": "dr kouadio annel",
    "DOC_466": "dr moktar isacha",
    "DOC_467": "dr n'guessan Ghislaine",
    "DOC_468": "dr kiakouou",
    "DOC_469": "dr koffi Fabrice",
    "DOC_470": "dr datte kouame",
    "DOC_471": "dr ouibop",
    "DOC_472": "dr gbery doffou",
    "DOC_473": "dr Dogbo Eric",
    "DOC_474": "dr kouassi Roseline",
    "DOC_475": "dr Ouattara ismaela",
    "DOC_476": "dr tia alain",
    "DOC_477": "dr bamka Richard",
    "DOC_478": "dr zanonu tchoko",
    "DOC_479": "dr boundwe Chretien",
    "DOC_480": "dr fatena yeli mamouna",
    "DOC_481": "dr Kouto mory",
    "DOC_482": "dr melonga Jonathan",
    "DOC_483": "dr Cissé mamourou",
    "DOC_484": "dr Kone yaya",
    "DOC_485": "Dr Camara",
    "DOC_486": "Dr Kouadio",
    "DOC_487": "Dr Yéboué",
    "DOC_488": "Dr Zégnédé Nadège",
    "DOC_489": "Dr Kodjo Valérie",
    "DOC_490": "Dr Alloh",
    "DOC_491": "Dr Kanga",
    "DOC_492": "Dr Kamissoko",
    "DOC_493": "Dr Touré",
    "DOC_494": "Dr Soumah",
    "DOC_495": "Dr Atsain",
    "DOC_496": "Dr Aka",
    "DOC_497": "IDE Bohiébi",
    "DOC_498": "IDE Badiél Abou",
    "DOC_499": "IDE Ishmael Kafando",
    "DOC_500": "Dr Bogui Herman",
    "DOC_501": "Mme Chantal",
    "DOC_502": "IDE Eugène",
    "DOC_503": "Dr N'Guessan Michel",
    "DOC_504": "Major Asi",
    "DOC_505": "Mme Diomandé",
    "DOC_506": "IDE Kouonga",
    "DOC_507": "IDE Kouassi Kouamé",
    "DOC_508": "IDE Bienvenue",
    "DOC_509": "IDE Nadia",
    "DOC_510": "IDE Ébé",
    "DOC_511": "Dr Agné",
    "DOC_512": "Dr Koulibaly",
    "DOC_513": "Zongo",
    "DOC_514": "Major M'Bra Marcel",
    "DOC_515": "IDE Neyaïa",
    "DOC_516": "IDE Achi",
    "DOC_517": "Mr Odo",
    "DOC_518": "Mr Fodjo",
    "DOC_519": "Mme Fanta",
    "DOC_520": "Mr Daniel",
    "DOC_521": "Dr Bilal",
    "DOC_522": "Dr Koné",
    "DOC_523": "Dr Kaho Moussa",
    "DOC_524": "Dr Marisol",
    "DOC_525": "Dr Assa",
    "DOC_526": "Mme Yapo",
    "DOC_527": "Mme Casuels",
    "DOC_528": "Dr N'Guessan",
    "DOC_529": "Dr Assa Constantïn",
    "DOC_530": "Dr Begué Patrice",
    "DOC_531": "Mme Soro Kaniija",
    "DOC_532": "Mme Beugué",
    "DOC_533": "IDE Zogoo Ibot",
    "DOC_534": "Mme Sombo Mariette",
    "DOC_535": "Mr Ibrahim",
    "DOC_536": "Mr Ouedraogo",
    "DOC_537": "Mr Bambaago",
    "DOC_538": "Mr Modibo",
    "DOC_539": "Dr N'Goran Christelle",
    "DOC_540": "IDE Eugene",
    "DOC_541": "Dr Amétcho Jean",
    "DOC_542": "Dr Yao Serge",
    "DOC_543": "Dr Touré Djénabou",
    "DOC_544": "Dr Bou Ange",
    "DOC_545": "Dr Boni",
    "DOC_546": "Dr N'Dri",
    "DOC_547": "Dr Bitohi",
    "DOC_548": "Major",
    "DOC_549": "Mme Gba Caritas",
    "DOC_550": "Dr Tuo",
    "DOC_551": "Dr Adjé Psu Vndi cité",
    "DOC_552": "Sage-femme Major Beblo",
    "DOC_553": "Dr Kassoum",
    "DOC_554": "Dr Synthia",
    "DOC_555": "Dr Katamoko",
    "DOC_556": "Dr Sakallo",
    "DOC_557": "Dr Anyan Jean",
    "DOC_558": "Dr Amétchi",
    "DOC_559": "Dr Sakaledia",
    "DOC_560": "Dr N'Goran",
    "DOC_561": "Dr Boni Fabrice",
    "DOC_562": "Dr Armand N'Di",
    "DOC_563": "Dr Atoby",
    "DOC_564": "Dr Tobea Ange",
    "DOC_565": "Dr Akpo Adjépo",
    "DOC_566": "IDE Baissolé",
    "DOC_567": "Dr Adou Boidy",
    "DOC_568": "Mme Dion",
    "DOC_569": "Dr Koman Rachel",
    "DOC_570": "Mr Kouamé",
    "DOC_571": "IDE André",
    "DOC_572": "IDE N'Guessan",
    "DOC_573": "IDE Atta Angèle",
    "DOC_574": "IDE Atsépri",
    "DOC_575": "IDE Kouassi",
    "DOC_576": "SF Sonda Mariette",
}

DOCTOR_OVERRIDES = {
    "DR ABOUSSOU STEPHANE": "DOC_001",
    "DR KOUROUMA WASSIRIKI": "DOC_002",
    "DR KRABOU SIDNEY": "DOC_003",
    "DR DOSSO AICHA": "DOC_004",
    "DR OUATTARA YAYA": "DOC_005",
    "DR INAGO CEDRIC": "DOC_006",
    "DR LOKOU ADJOH": "DOC_007",
    "DR N'KON KOUAME": "DOC_008",
    "DR YAF KRA KOFFI": "DOC_009",
    "DR ASSI BRICE": "DOC_010",
    "DR ASSOUMA RITA": "DOC_011",
    "DR TRAORE MEDE": "DOC_012",
    "DR TOUALY MADOCHE": "DOC_013",
    "DR TANOE ROSE": "DOC_014",
    "DR GNOUHOUR YAHE": "DOC_015",
    "DR MELEDJE GRACE": "DOC_016",
    "DR ALEGRA ABRAKON": "DOC_017",
    "DR AMON SIDONIE": "DOC_018",
    "DR OGOU VALENTIN": "DOC_019",
    "DR DJOUMAN AUDREY": "DOC_020",
    "DR DONGO KOUAME": "DOC_021",
    "DR AMON ANGE": "DOC_022",
    "IDE KOFFIF KOUAME": "DOC_023",
    "DR KOUAKOU ESTELLRE": "DOC_024",
    "DR TAH BI JULES": "DOC_025",
    "DR BAMBA MALIKA": "DOC_026",
    "DR N'GUESSAN DIARASSOUBA": "DOC_027",
    "DR KOUADIO BAISSA": "DOC_028",
    "DR N'ZI YAO": "DOC_029",
    "DR KABORE GEDEON": "DOC_030",
    "DR AHONON RICHARD": "DOC_031",
    "DR AMANI ANZIAN": "DOC_032",
    "DR ASSANDE GUILLAUME": "DOC_033",
    "IDE TCHOUMOU NATALIE": "DOC_034",
    "IDE EBONI EZECKIEL": "DOC_035",
    "DR YAO YANN": "DOC_036",
    "DR MANGOUA PAUL": "DOC_037",
    "DR KONAN LUC": "DOC_038",
    "DR BILE EKRA": "DOC_039",
    "DR JACQUES KOUAKOU": "DOC_040",
    "SF BOKA EPSE KOUAME": "DOC_041",
    "DR KOUAME STEPHANE": "DOC_042",
    "DR KOUSSAN FRANCOIS": "DOC_043",
    "DR AWA ATTE": "DOC_044",
    "DR ASSI ANGBA BRICE": "DOC_045",
    "DR EDI BOFFOU": "DOC_046",
    "IDE GBEGOU MOIEL": "DOC_047",
    "DR KPEA IVAN CEDRIC": "DOC_048",
    "DR KOUASSI KOFFI": "DOC_049",
    "DR MENOIT GREGOIRE": "DOC_050",
    "DR KOUASSI NHEL": "DOC_051",
    "DR GILE MOHAMED": "DOC_052",
    "SF BELLOU ARIANE": "DOC_053",
    "IDE AKA TANDJI HONORE": "DOC_054",
    "DR KONDJI K. OZEH": "DOC_055",
    "DR KONAN JOACHIN": "DOC_056",
    "DR OUATTARA EL YATA": "DOC_057",
    "DR BAH GRAH GYRI": "DOC_058",
    "IDE KOUADIO SERGE": "DOC_059",
    "DR MENOIT MAHI DOUGLAS": "DOC_060",
    "DR KOUAME CLAVER": "DOC_061",
    "IDE AKA JEAN RENE": "DOC_062",
    "IDE YOBOU EPSE ADDN": "DOC_063",
    "SF AKE ROSANI": "DOC_064",
    "SF DIALLO NÉE KOUAME": "DOC_065",
    "SF SONAN ANDRE H": "DOC_066",
    "DR FENI ROSINI": "DOC_067",
    "DR BILE BERTRAND": "DOC_068",
    "DR BAH LUCIEN": "DOC_069",
    "DR DOHI BI GOA L": "DOC_070",
    "DR KONE ADAMA": "DOC_071",
    "DR KOUAKOU GINETE": "DOC_072",
    "DR N'GUESSAN K. ETIENNE": "DOC_073",
    "IDE KONE DRAMANE": "DOC_074",
    "DR KPEL N'GUESSAN": "DOC_075",
    "DR MFOUMANE DOUGLAS": "DOC_076",
    "IDE SOUMAHORO LASSINA": "DOC_077",
    "IDE KOUASSI GNANGRE": "DOC_078",
    "DR ODEHE ANNICK": "DOC_079",
    "DR ALLEGRA ABRAHAM": "DOC_080",
    "SF TRAORE BIN TOU": "DOC_081",
    "DR ALLO BOU": "DOC_082",
    "DR VEDGOUNOU ROMEO": "DOC_083",
    "IDE ANOMA ELISABETH": "DOC_084",
    "IDE KOUAME AHOU A.": "DOC_085",
    "SF YAO NÉE BROU AKISSI": "DOC_086",
    "SF DIALLO NÉE SANFO": "DOC_087",
    "DR YEO KPOUNOU ASSITA": "DOC_088",
    "DR NARCISSE KOUADIO": "DOC_089",
    "DR KOFFI KOUASSI KANI": "DOC_090",
    "DR DIAGRA OFELA I.": "DOC_091",
    "DR KOFFI PARFAIT": "DOC_092",
    "DR GNAHORE DAVID": "DOC_093",
    "DR MENOIT GREGOIRE H.": "DOC_094",
    "DR AHEBROU F.": "DOC_095",
    "IDE AMIAN BEATRICE": "DOC_096",
    "DR KOUAKOU YAH": "DOC_097",
    "ACHO ROMEO": "DOC_098",
    "DR AKA PASCAL": "DOC_099",
    "DR KASSI CHRISTOPHE": "DOC_100",
    "DR KOFFI AYA ROSINE F.": "DOC_101",
    "SF EDI MARIE": "DOC_102",
    "SF KOFFI NÉE KOUADJO": "DOC_103",
    "SF SANOGO NÉE DIARRASO": "DOC_104",
    "SF KOFFI NÉE DJAKANA": "DOC_105",
    "IDE HOUEGNON RODRIGUE": "DOC_106",
    "DR YAO KOUAKOU": "DOC_107",
    "DR N'GUESSAN HELENE": "DOC_108",
    "IDE YAO HELENE": "DOC_109",
    "DR GAUZE JEAN CLAUDE": "DOC_110",
    "IDE YAO KOUADIO ALFRED": "DOC_111",
    "DR N'DA TOTHU D. N.": "DOC_112",
    "IDE AKOTO GUIA M.": "DOC_113",
    "DR YAO KOFFI MATHURIN": "DOC_114",
    "DR CISSE FATIMATA": "DOC_115",
    "IDE TENI ANGELIQUE": "DOC_116",
    "DR AMATA ERIC": "DOC_117",
    "DR GOUESSE Y. PATRICE": "DOC_118",
    "DR KPELE YABA B.": "DOC_119",
    "KOFFI DIDIER": "DOC_120",
    "TOURÉ TAHA ÉPOUSE KOUAMÉ": "DOC_121",
    "ADJOUMAN HERVÉ": "DOC_122",
    "BALOU DIOP": "DOC_123",
    "BOTTI LOU NÉDÈGE": "DOC_124",
    "N'GUESSAN VALERIE": "DOC_125",
    "ESNEL FRANCK": "DOC_126",
    "DIALLOU GÉRALD": "DOC_127",
    "BODEL PARFAIT": "DOC_128",
    "BODEL HYACINTHE": "DOC_129",
    "BAWAR FIRMIN": "DOC_130",
    "ABDALLAH BECOÜÉ": "DOC_131",
    "KONE IBRAHIM": "DOC_132",
    "ALLIMI LAWAL": "DOC_133",
    "KTO EUGÉNIE": "DOC_134",
    "BANSANON FORTUNE": "DOC_135",
    "NÉHO MOISE": "DOC_136",
    "BAMI ISMAÉL": "DOC_137",
    "NIHO MARIE": "DOC_138",
    "YACINE MALICK": "DOC_139",
    "AGBO NIAM NAZAIRE": "DOC_140",
    "DIOMANDÉ KATIENOU": "DOC_141",
    "GNANKEY VENISE": "DOC_142",
    "N'DRI": "DOC_143",
    "DOUZOUA MARC": "DOC_144",
    "MC AMALO": "DOC_145",
    "TANO SIMON": "DOC_146",
    "N' TAYE SEU NOMANTO": "DOC_147",
    "AKAHOU STÉPHANIE": "DOC_148",
    "DATAMLA KONÉ": "DOC_149",
    "KOFFI CHARLES": "DOC_150",
    "GULAI GBAZA ADÉLA": "DOC_151",
    "DIMASSOUBA TCHLAGBAN ALASSANE": "DOC_152",
    "KTO PAULINE": "DOC_153",
    "KOUAMÉ LOU ÉLODIE": "DOC_154",
    "OKE": "DOC_155",
    "KOCHI THIERRY AIME": "DOC_156",
    "ETTE GOULOU": "DOC_157",
    "KONE ACHILLE": "DOC_158",
    "ALASSANE AGIBA": "DOC_159",
    "RODRIGUE KASSI N'GUESSAN": "DOC_160",
    "YAPI ERIC": "DOC_161",
    "DENHE CHARLES EMMANUEL": "DOC_162",
    "KESSÉ CHIMÈNE": "DOC_163",
    "KPOTA BONGO LUCIS": "DOC_164",
    "KASSI KADJO MARTINE": "DOC_165",
    "DINDJI SALOMON": "DOC_166",
    "N'GUESSAN GUILLAUME LANDRY": "DOC_167",
    "MÉITÉ ALIZETA": "DOC_168",
    "ZAOULI LOU ANGE": "DOC_169",
    "SIKALI ARISTIDE": "DOC_170",
    "ANKA ZÉPHYRIN": "DOC_171",
    "KOUSSI AMAN FLORENTINE": "DOC_172",
    "WASSIOU ORO SIRIYA ORO WASSIOU": "DOC_173",
    "BARRY ISMAEL": "DOC_174",
    "KRA KOUDIO HONORÉ": "DOC_175",
    "TIERO KADIA RIANG": "DOC_176",
    "ADBALLAH (0208214603)": "DOC_177",
    "ASSIA MIGNELI": "DOC_178",
    "DJAMALA AHOU": "DOC_179",
    "ASSIAVE LITÉ": "DOC_180",
    "FADIGA NADIA": "DOC_181",
    "BEDA JEAN ALPHONSE": "DOC_182",
    "BAKAYOKO HAROUN": "DOC_183",
    "BODOLO IGNACE": "DOC_184",
    "DIGBE MAGALI": "DOC_185",
    "N' MOULA SANDRINE JACKY": "DOC_186",
    "BALO MIREILLE": "DOC_187",
    "SOURAKATA CAMARA": "DOC_188",
    "IRIE SAMUEL": "DOC_189",
    "ROMARIC KOUAKOU": "DOC_190",
    "KONIN MIALIA": "DOC_191",
    "MAMADOU COULIBALY": "DOC_192",
    "KOUA ABOULI KOUAKOU": "DOC_193",
    "KOUACOU ANKA ADJO": "DOC_194",
    "KLAIDO ODILE": "DOC_195",
    "KALOGO ARAFAT": "DOC_196",
    "ABONI YVES ROLAND KOFFI": "DOC_197",
    "SANOKO FACIMA": "DOC_198",
    "KONAN BOHOUSSOU ZENE CAROLE": "DOC_199",
    "BAHI JUNIOR": "DOC_200",
    "KOUAKOU KOUADIO": "DOC_201",
    "SEKA CHERIF LACINA": "DOC_202",
    "DOUMBIA MOUSSA": "DOC_203",
    "CISSE SABARY": "DOC_204",
    "KOUASSI ALFRED": "DOC_205",
    "KRA IDRISS OUATTARA": "DOC_206",
    "KOUAME INFOU FAUSTIN": "DOC_207",
    "COULIBALY TIMAN": "DOC_208",
    "LOIZOH LOUAME": "DOC_209",
    "N'GUESSAN KOUAME": "DOC_210",
    "GOUANDEU NICAISE": "DOC_211",
    "TOURE MYRIAM": "DOC_212",
    "JULIE ROMEO": "DOC_213",
    "KONAN PACOME": "DOC_214",
    "DIALLO CHEICK OUMAR": "DOC_215",
    "KONE SOMBO": "DOC_216",
    "COULIBALY ALILCE": "DOC_217",
    "KPASSO MARINA": "DOC_218",
    "KOUAKOU JULIEN": "DOC_219",
    "TIADA AMINATA TOURÉ": "DOC_220",
    "TOURÉ PAMIGEAN": "DOC_221",
    "KASSOGUÉ MARLENCE": "DOC_222",
    "ADJA MAGBOIR": "DOC_223",
    "OUGONOU MARINA": "DOC_224",
    "SIRIE HYPOLITE FULGENCE": "DOC_225",
    "BILA ARIGNAN ESTELLE": "DOC_226",
    "QUIHI ADÈLE": "DOC_227",
    "ADOUGRA ABRAHAM": "DOC_228",
    "KANAMOKO": "DOC_229",
    "SEGBENG HERMANA": "DOC_230",
    "DENÉ FATOUMATA": "DOC_231",
    "LAPA EVELYNE": "DOC_232",
    "KONAN BÉNÉDICTE": "DOC_233",
    "DIORASSOUBA AMINATA": "DOC_234",
    "MR SIMON": "DOC_235",
    "QUEDRAOGO LAYEUL": "DOC_236",
    "KOUADIO WILFRIED": "DOC_237",
    "KOUAKOU SANDRINE": "DOC_238",
    "ALLEH YANNICK": "DOC_239",
    "BAMBA NAWA CHEIFF": "DOC_240",
    "KOUADIO LOUIS JANVIER": "DOC_241",
    "AG EULYONE": "DOC_242",
    "ZOUE URBAIN": "DOC_243",
    "ASSANDE RUNDE": "DOC_244",
    "SOUMAHORO SALIMATA": "DOC_245",
    "YAYA RIBECA": "DOC_246",
    "KOUASSI ZAKOUA": "DOC_247",
    "KOUADIO SAMUEL": "DOC_248",
    "AGAFOU BERTRAND": "DOC_249",
    "GNAGNE VALERIE": "DOC_250",
    "BODJI LOUIS": "DOC_251",
    "GOZE ANDRE": "DOC_252",
    "ABOU FELIX": "DOC_253",
    "KOUASSI YAO": "DOC_254",
    "AGBEDJE BÉATRICE": "DOC_255",
    "JEAN CLAUDE NADO": "DOC_256",
    "GOUELI ARISTIDE": "DOC_257",
    "DAHIN JEAN": "DOC_258",
    "ZAMPOL SILIMANE": "DOC_259",
    "PKLE N'GUESSAN": "DOC_260",
    "KAKOU AMBROISINE": "DOC_261",
    "KOUAME BORIS": "DOC_262",
    "ZEDJA GEDEON": "DOC_263",
    "NGUESSAN ALPHONSE": "DOC_264",
    "TOURE KILOUFOUOH": "DOC_265",
    "COULIBALY GNATIOLO": "DOC_266",
    "DIOMANDE HAMED": "DOC_267",
    "BROU MICHEL": "DOC_268",
    "GOGBEU ELYSE": "DOC_269",
    "ZAOULI BI ARNAUD": "DOC_270",
    "KENGANI ALPHONSE": "DOC_271",
    "BENIE N'DA": "DOC_272",
    "TOURE BIMAILA": "DOC_273",
    "AFFINGEL": "DOC_274",
    "KOUMON GHISLAIN": "DOC_275",
    "COULIBALY AMINATA": "DOC_276",
    "AFFOUMANI DOUGLAS": "DOC_277",
    "KONAN ARSENE": "DOC_278",
    "OUATTARA": "DOC_279",
    "KOUAD ANDERSON": "DOC_280",
    "KINIMISSIBO SIKA": "DOC_281",
    "FAYE ESSETCHI": "DOC_282",
    "GBONA AMBROISE": "DOC_283",
    "PAUL MEMEL": "DOC_284",
    "AW TIDIANE": "DOC_285",
    "BEUGRE ESMEL": "DOC_286",
    "VODOUNOU ROMEO": "DOC_287",
    "DOH GUY": "DOC_288",
    "AGA PATRICK": "DOC_289",
    "GNEGA GNABRY": "DOC_290",
    "OUATTARA MARIAM": "DOC_291",
    "OUFFOUE ROXANNE": "DOC_292",
    "SEKONGO NAHOUA": "DOC_293",
    "MIME ANOUABA ROME": "DOC_294",
    "NEA TIDE": "DOC_295",
    "ABO REIJE": "DOC_296",
    "BOUSCHOL OUA LABINE": "DOC_297",
    "NORO": "DOC_298",
    "GNAGNON ROXANNE": "DOC_299",
    "NAKAYOKO BIN TOU": "DOC_300",
    "ROLAND AMOUYON": "DOC_301",
    "YCHIKA ANGE": "DOC_302",
    "KOUAKOU AHOU BOSTLINE": "DOC_303",
    "WANGBANA AWA": "DOC_304",
    "KONE KANAKONON": "DOC_305",
    "SALIFOU TEHINI": "DOC_306",
    "LOU BI INI": "DOC_307",
    "GBEHE TOU ANARETE": "DOC_308",
    "AHI N'GESSAN": "DOC_309",
    "SEKONGO FATOUMATA": "DOC_310",
    "SIAHE GERMAIN": "DOC_311",
    "KOUAME MICHAEL": "DOC_312",
    "KOUASSI VIVIANE": "DOC_313",
    "JULIEN MARCEL": "DOC_314",
    "KOUADIO BERNADETTE": "DOC_315",
    "BABILE BONIFACE": "DOC_316",
    "KOFFI N'DRI": "DOC_317",
    "OLIVIER KOUADIO": "DOC_318",
    "BASSAN JONAS": "DOC_319",
    "N'DRI ALEXANDRE": "DOC_320",
    "DOSSO MAMADOU": "DOC_321",
    "GOULI CHERIE": "DOC_322",
    "IBADO FÉLIX": "DOC_323",
    "BADO NOUVOU": "DOC_324",
    "WILLY MEMEL": "DOC_325",
    "INOTTI PRISCA": "DOC_326",
    "WANGRAGUA ABOUBAKAR": "DOC_327",
    "YAGUE MARCEL": "DOC_328",
    "SAGOU MARIE SOLANGE": "DOC_329",
    "TOFANA": "DOC_330",
    "ABO YOUSSOUF": "DOC_331",
    "EUGENE TANDJI": "DOC_332",
    "AKRE PIERRE": "DOC_333",
    "SEHME YACOUBA": "DOC_334",
    "DODO MARIE JOSEE": "DOC_335",
    "SERWE SALIF": "DOC_336",
    "ROA KOUASSI": "DOC_337",
    "GAMI RI": "DOC_338",
    "ZORON CHEICK": "DOC_339",
    "CAMARA KARIM": "DOC_340",
    "LOBE LILIANE": "DOC_341",
    "KOUAME AXELLE": "DOC_342",
    "KOFFI ARSÈNE": "DOC_343",
    "KONE AICHA": "DOC_344",
    "SOKOUA LOUISE": "DOC_345",
    "GOUE GONTO BORIS": "DOC_346",
    "KONE DRAMANE": "DOC_347",
    "GOULI KOUADIO": "DOC_348",
    "KONAN NARCISSE": "DOC_349",
    "GNAGNE FREDERIC": "DOC_350",
    "APKA ESMEL": "DOC_351",
    "ESMELY INGRID": "DOC_352",
    "KANGA PARFAIT": "DOC_353",
    "TOUE APOLLINE": "DOC_354",
    "OULAI CYPRIEN": "DOC_355",
    "KOUADIO MARIUS": "DOC_356",
    "APKA RACHELLE": "DOC_357",
    "REAMY BAZIE": "DOC_358",
    "KOFFI ALEXIS": "DOC_359",
    "DIARRA MOHAMED": "DOC_360",
    "KADJA ANOH": "DOC_361",
    "KONE FANTAMAN": "DOC_362",
    "DR GANSERE DAVID": "DOC_363",
    "DR MAPOUT BIENVENUE": "DOC_364",
    "DR CHARED EDDICHO": "DOC_365",
    "DR KOUADOSU FRANCIS": "DOC_366",
    "DR N'DJERE": "DOC_367",
    "DR KOUASSI LANDRY": "DOC_368",
    "DR KOUAKOU AMENAN NATHALIE": "DOC_369",
    "DR NIKADI DYLANE": "DOC_370",
    "DR AKANDIA AKA OLIVE": "DOC_371",
    "DEMBELE HAMED": "DOC_372",
    "DR BIAMI DIANE": "DOC_373",
    "KANDAM HERNA": "DOC_374",
    "DR YAMARA MYRIAM": "DOC_375",
    "DR DIPOO PHILIPPE": "DOC_376",
    "DR AGBO ANA": "DOC_377",
    "KONAN EMMA KONATÉ": "DOC_378",
    "DR YOUKAM ROCTAND": "DOC_379",
    "MR KPAKPO GERMAIN": "DOC_380",
    "MR OUADVEJO": "DOC_381",
    "MME DJIKANO JUDITH": "DOC_382",
    "MR OUADRAOGO ABDOUL": "DOC_383",
    "MME N'DRI RACHELLE": "DOC_384",
    "MME KONAN EMILIE": "DOC_385",
    "MME GOGBO MARTINE": "DOC_386",
    "MR AKPOESA AZOUBA": "DOC_387",
    "MME AORE GRÀCE": "DOC_388",
    "MME TOURÉ MARIE TANO": "DOC_389",
    "MME N'TAKPE MARTHE": "DOC_390",
    "MME ANTHONY TATIANA": "DOC_391",
    "MME BOUATONGU HABIBA": "DOC_392",
    "MME KOUADIO SANDRINE": "DOC_393",
    "MME DATTE FATOUMA": "DOC_394",
    "MME OUROHO": "DOC_395",
    "MME AICHA ADELINE": "DOC_396",
    "MME ABOUSSOU NICOLE": "DOC_397",
    "MME DIOMANDE": "DOC_398",
    "PR ODJALU": "DOC_399",
    "MME N'GOLO DR": "DOC_400",
    "DR KOFFI O": "DOC_401",
    "DR DIOMANDE ZENAB": "DOC_402",
    "DR KOUADIO IOL": "DOC_403",
    "DR TANO": "DOC_404",
    "DR AGHAODRA": "DOC_405",
    "DR BARRY": "DOC_406",
    "DR MACOTO": "DOC_407",
    "DR ATOUNMI": "DOC_408",
    "CVA TIHIO": "DOC_409",
    "DR OUATTARA": "DOC_410",
    "DR DAO A": "DOC_411",
    "YA KOUA": "DOC_412",
    "DR KASSA": "DOC_413",
    "DR YAO": "DOC_414",
    "DR GENDO IDRICH": "DOC_415",
    "DR KONAN": "DOC_416",
    "DR OUAN": "DOC_417",
    "DR MOROMO": "DOC_418",
    "PR ALLA NUMBA": "DOC_419",
    "DR BEKOOA": "DOC_420",
    "DR COULIBALY": "DOC_421",
    "DR BOM FLORA": "DOC_422",
    "DR MATHEAAT": "DOC_423",
    "DR YAPI BÉNÉDICTE": "DOC_424",
    "DR TOUA": "DOC_425",
    "DR BABATUNDE": "DOC_426",
    "DR INAHOUNO": "DOC_427",
    "DR ABOUBA": "DOC_428",
    "DR RONGWA TANCIN": "DOC_429",
    "DR TRESEK BRASCAM": "DOC_430",
    "DR TRESEK TESCOK MARY": "DOC_431",
    "DR OOOUH": "DOC_432",
    "DR BAAA": "DOC_433",
    "MAYO": "DOC_434",
    "DR CASEY AIME": "DOC_435",
    "DR COULIBALY YAYA": "DOC_436",
    "DR BAMBA ABOUBACAR": "DOC_437",
    "DE BPAMI NINA": "DOC_438",
    "DR OUAHOU KASYA": "DOC_439",
    "DR BANA PAUL": "DOC_440",
    "DR BOM KOUADIO": "DOC_441",
    "MME COUASTY": "DOC_442",
    "DR RITA": "DOC_443",
    "DR MEITE": "DOC_444",
    "DR HAMID LALA": "DOC_445",
    "DR DIOMANDE MOHAMED": "DOC_446",
    "DR MEITE MARINA": "DOC_447",
    "DR OUATTARI DJAKOURY": "DOC_448",
    "PR AG ESSILIER": "DOC_449",
    "DR KOUADIO ROSELINE": "DOC_450",
    "DR KOKRO MICHEL": "DOC_451",
    "DR MARE MARIAN": "DOC_452",
    "DR SUISA VIANNEY": "DOC_453",
    "DR EDI MEELYNE": "DOC_454",
    "DR NIAHE VIANNEY": "DOC_455",
    "DR DIABA DENI": "DOC_456",
    "DR DIABA LOUAECO": "DOC_457",
    "DR ETTIENANGO": "DOC_458",
    "DR OAHO SANDRINE": "DOC_459",
    "DR TOURÉ ANGELLE": "DOC_460",
    "DR OUHONGO": "DOC_461",
    "DR MAHIO DOMINIQUE": "DOC_462",
    "DR TCHOUMOU CHRISTOPHE": "DOC_463",
    "DR MOITAM NEDIOU": "DOC_464",
    "DR KOUADIO ANNEL": "DOC_465",
    "DR MOKTAR ISACHA": "DOC_466",
    "DR N'GUESSAN GHISLAINE": "DOC_467",
    "DR KIAKOUOU": "DOC_468",
    "DR KOFFI FABRICE": "DOC_469",
    "DR DATTE KOUAME": "DOC_470",
    "DR OUIBOP": "DOC_471",
    "DR GBERY DOFFOU": "DOC_472",
    "DR DOGBO ERIC": "DOC_473",
    "DR KOUASSI ROSELINE": "DOC_474",
    "DR OUATTARA ISMAELA": "DOC_475",
    "DR TIA ALAIN": "DOC_476",
    "DR BAMKA RICHARD": "DOC_477",
    "DR ZANONU TCHOKO": "DOC_478",
    "DR BOUNDWE CHRETIEN": "DOC_479",
    "DR FATENA YELI MAMOUNA": "DOC_480",
    "DR KOUTO MORY": "DOC_481",
    "DR MELONGA JONATHAN": "DOC_482",
    "DR CISSÉ MAMOUROU": "DOC_483",
    "DR KONE YAYA": "DOC_484",
    "DR CAMARA": "DOC_485",
    "DR KOUADIO": "DOC_486",
    "DR YÉBOUÉ": "DOC_487",
    "DR ZÉGNÉDÉ NADÈGE": "DOC_488",
    "DR KODJO VALÉRIE": "DOC_489",
    "DR ALLOH": "DOC_490",
    "DR KANGA": "DOC_491",
    "DR KAMISSOKO": "DOC_492",
    "DR TOURÉ": "DOC_493",
    "DR SOUMAH": "DOC_494",
    "DR ATSAIN": "DOC_495",
    "DR AKA": "DOC_496",
    "IDE BOHIÉBI": "DOC_497",
    "IDE BADIÉL ABOU": "DOC_498",
    "IDE ISHMAEL KAFANDO": "DOC_499",
    "DR BOGUI HERMAN": "DOC_500",
    "MME CHANTAL": "DOC_501",
    "IDE EUGÈNE": "DOC_502",
    "DR N'GUESSAN MICHEL": "DOC_503",
    "MAJOR ASI": "DOC_504",
    "MME DIOMANDÉ": "DOC_505",
    "IDE KOUONGA": "DOC_506",
    "IDE KOUASSI KOUAMÉ": "DOC_507",
    "IDE BIENVENUE": "DOC_508",
    "IDE NADIA": "DOC_509",
    "IDE ÉBÉ": "DOC_510",
    "DR AGNÉ": "DOC_511",
    "DR KOULIBALY": "DOC_512",
    "ZONGO": "DOC_513",
    "MAJOR M'BRA MARCEL": "DOC_514",
    "IDE NEYAÏA": "DOC_515",
    "IDE ACHI": "DOC_516",
    "MR ODO": "DOC_517",
    "MR FODJO": "DOC_518",
    "MME FANTA": "DOC_519",
    "MR DANIEL": "DOC_520",
    "DR BILAL": "DOC_521",
    "DR KONÉ": "DOC_522",
    "DR KAHO MOUSSA": "DOC_523",
    "DR MARISOL": "DOC_524",
    "DR ASSA": "DOC_525",
    "MME YAPO": "DOC_526",
    "MME CASUELS": "DOC_527",
    "DR N'GUESSAN": "DOC_528",
    "DR ASSA CONSTANTÏN": "DOC_529",
    "DR BEGUÉ PATRICE": "DOC_530",
    "MME SORO KANIIJA": "DOC_531",
    "MME BEUGUÉ": "DOC_532",
    "IDE ZOGOO IBOT": "DOC_533",
    "MME SOMBO MARIETTE": "DOC_534",
    "MR IBRAHIM": "DOC_535",
    "MR OUEDRAOGO": "DOC_536",
    "MR BAMBAAGO": "DOC_537",
    "MR MODIBO": "DOC_538",
    "DR N'GORAN CHRISTELLE": "DOC_539",
    "IDE EUGENE": "DOC_540",
    "DR AMÉTCHO JEAN": "DOC_541",
    "DR YAO SERGE": "DOC_542",
    "DR TOURÉ DJÉNABOU": "DOC_543",
    "DR BOU ANGE": "DOC_544",
    "DR BONI": "DOC_545",
    "DR N'DRI": "DOC_546",
    "DR BITOHI": "DOC_547",
    "MAJOR": "DOC_548",
    "MME GBA CARITAS": "DOC_549",
    "DR TUO": "DOC_550",
    "DR ADJÉ PSU VNDI CITÉ": "DOC_551",
    "SAGE-FEMME MAJOR BEBLO": "DOC_552",
    "DR KASSOUM": "DOC_553",
    "DR SYNTHIA": "DOC_554",
    "DR KATAMOKO": "DOC_555",
    "DR SAKALLO": "DOC_556",
    "DR ANYAN JEAN": "DOC_557",
    "DR AMÉTCHI": "DOC_558",
    "DR SAKALEDIA": "DOC_559",
    "DR N'GORAN": "DOC_560",
    "DR BONI FABRICE": "DOC_561",
    "DR ARMAND N'DI": "DOC_562",
    "DR ATOBY": "DOC_563",
    "DR TOBEA ANGE": "DOC_564",
    "DR AKPO ADJÉPO": "DOC_565",
    "IDE BAISSOLÉ": "DOC_566",
    "DR ADOU BOIDY": "DOC_567",
    "MME DION": "DOC_568",
    "DR KOMAN RACHEL": "DOC_569",
    "MR KOUAMÉ": "DOC_570",
    "IDE ANDRÉ": "DOC_571",
    "IDE N'GUESSAN": "DOC_572",
    "IDE ATTA ANGÈLE": "DOC_573",
    "IDE ATSÉPRI": "DOC_574",
    "IDE KOUASSI": "DOC_575",
    "SF SONDA MARIETTE": "DOC_576",
}

_DOCTOR_INDEX = []  # dynamically populated at runtime

def build_doctor_index(doctor_names: list):
    """
    Call once at app startup with all doctor names from visit tracker sheets.
    Deduplicates and normalizes for fuzzy matching.
    """
    global _DOCTOR_INDEX
    cleaned = set()
    for name in doctor_names:
        n = str(name).strip()
        if n and n.lower() not in ("nan", "nom /pernom", ""):
            cleaned.add(n)
    _DOCTOR_INDEX = sorted(cleaned)
    return _DOCTOR_INDEX

def normalize_doctor(raw: str, threshold: int = 72) -> str:
    """
    Returns closest canonical doctor name using exact mapping first,
    then visit tracker index fuzzy match. Falls back to cleaned raw name.
    """
    if not raw or str(raw).strip() in ("", "nan"):
        return "UNKNOWN"
    clean = str(raw).strip().upper()

    if clean in DOCTOR_OVERRIDES:
        doc_id = DOCTOR_OVERRIDES[clean]
        return DOCTOR_CANONICAL.get(doc_id, doc_id)

    clean_original_case = str(raw).strip()
    if not _DOCTOR_INDEX:
        return clean_original_case  # index not built yet, return as-is

    match, score, _ = process.extractOne(
        clean_original_case, _DOCTOR_INDEX, scorer=fuzz.token_sort_ratio
    )
    return match if score >= threshold else clean_original_case


# ─────────────────────────────────────────────────────────────
# 6. DISTRIBUTORS
# ─────────────────────────────────────────────────────────────

DISTRIBUTOR_CANONICAL = {
    "DIST_01": "UBIPHARM / LABOREX",
    "DIST_02": "COPHARMED / LABOREX",
    "DIST_03": "TEDIS",
    "DIST_04": "DPCI",
}

DISTRIBUTOR_OVERRIDES = {
    "UBIPHARM/LABOREX": "DIST_01", "UBIPHARM / LABOREX": "DIST_01",
    "COPHARMED/LABOREX": "DIST_02", "COPHARMED / LABOREX": "DIST_02",
    "TEDIS": "DIST_03",
    "DPCI": "DIST_04",
}

def normalize_distributor(raw: str) -> str:
    clean = str(raw).strip().upper()
    return DISTRIBUTOR_OVERRIDES.get(clean, "UNKNOWN")

def distributor_display_name(dist_id: str) -> str:
    return DISTRIBUTOR_CANONICAL.get(dist_id, dist_id)


# ─────────────────────────────────────────────────────────────
# 7. CURRENCY HELPER
# ─────────────────────────────────────────────────────────────

FCFA_TO_EUR = 655.97

def to_eur(fcfa: float) -> float:
    return round(fcfa / FCFA_TO_EUR, 2)

def to_fcfa(eur: float) -> float:
    return round(eur * FCFA_TO_EUR, 0)


# ─────────────────────────────────────────────────────────────
# QUICK SELF-TEST
# ─────────────────────────────────────────────────────────────
if __name__ == "__main__":
    tests = [
        ("MR", normalize_mr, [
            "calmance", "jamab frank", "jitender sir", "VALERY",
            "in list of ahioua", "JITENDRA/CLEMANCE", "1"
        ]),
        ("PRODUCT", normalize_product, [
            "KLINDEZ-M", "NOZEE", "AVTEX", "OMECID,", "FUSIZEX-INJ",
            "AVETEX(417 ) DEC-& JAN", "ARTEQUIN LACTAB 300/375 BT6"
        ]),
        ("ACTIVITY", normalize_activity, [
            "COMISSION", "PETITE DEJOUNER", "PETIT DEJOUNER", "MOTIVATION "
        ]),
        ("TERRITORY", normalize_territory, [
            "YOPOUGON OUEST", "YOUPOUGON EAST", "COCODI", "KOUMASSI+MARCORI+PORT BOUET"
        ]),
    ]
    for label, fn, cases in tests:
        print(f"\n=== {label} ===")
        for c in cases:
            result = fn(c)
            print(f"  '{c}' -> {result}")